//Actions from Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const EDIT_SEND_NOTIFY_SUCCESS = 'EDIT_SEND_NOTIFY_SUCCESS';
export const EDIT_SEND_NOTIFY_ERROR = 'EDIT_SEND_NOTIFY_ERROR';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';

//Actions from Charity
export const GET_ALL_CHARITIES_SUCCESS = 'GET_ALL_CHARITIES_SUCCESS';
export const GET_ALL_CHARITIES_ERROR = 'GET_ALL_CHARITIES_ERROR';
export const GET_CHARITY_NUMBER_SUCCESS = 'GET_CHARITY_NUMBER_SUCCESS';
export const GET_CHARITY_NUMBER_ERROR = 'GET_CHARITY_NUMBER_ERROR';

//Actions from Solicitation
export const CREATE_SOLICITATION_SUCCESS = 'CREATE_SOLICITATION_SUCCESS';
export const CREATE_SOLICITATION_ERROR = 'CREATE_SOLICITATION_ERROR';
export const GET_DONATION_NUMBER_SUCCESS = 'GET_DONATION_NUMBER_SUCCESS';
export const GET_DONATION_NUMBER_ERROR = 'GET_DONATION_NUMBER_ERROR';
export const GET_SOLICITATIONS_USER_SUCCESS = 'GET_SOLICITATIONS_USER_SUCCESS';
export const GET_SOLICITATIONS_USER_ERROR = 'GET_SOLICITATIONS_USER_ERROR';
export const GET_SOLICITATION_DETAIL_SUCCESS =
  'GET_SOLICITATION_DETAIL_SUCCESS';
export const GET_SOLICITATION_DETAIL_ERROR = 'GET_SOLICITATION_DETAIL_ERROR';
export const CANCEL_SOLICITATION_SUCCESS = 'CANCEL_SOLICITATION_SUCCESS';
export const CANCEL_SOLICITATION_ERROR = 'CANCEL_SOLICITATION_ERROR';
